# .github/workflows/bun.yml
name: Bun CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: antongolub/action-setup-bun@v1.13.1
        with:
          bun-version: v1.x # Uses latest bun 1
      - run: bun x jsr add @cross/test @std/assert @cross/runtime @cross/deepmerge # Installs dependencies
      - run: bun test # Runs the tests